[package]
name = "vgtk-manpages"
version = "0.1.0"
authors = ["Hilmar Gústafsson <hilmargustafs@gmail.com>"]
edition = "2018"

[dependencies]
webkit2gtk = "0.9.2"
vgtk = "0.2.1"
pretty_env_logger = "0.4"
